### ISSUE TITLE
Custom font size selection

### ISSUE THREAD

**Issue by declider** [giambaJ/jChat#4]
Use custom value with PT over 3 variants like now

![image](https://user-images.githubusercontent.com/62831308/129216272-d4c1240f-29a2-407a-a787-42888cd04df8.png)

**Comment by giambaJ** [comment]
The problem with custom font size is that everything else depends on it. Emote size, badge size, line height, spacing and whatnot would need to be changed accordingly to match your custom font size value. It's not impossible, but I would need to rewrite a lot of stuff to make the rendering fully dynamic. Sounds like a lot of work for a trivial feature, since you can easily resize the OBS browser source if you think the chat is too big.
